name: setup-linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Run build
      run: |
        python3 -m unittest tests.parsersuite
        python3 -m tests.test
        python3 -m PyInstaller --name="amanda" \
        --onefile --console amanda/__.main__.py 
        sudo python3 setup.py
        amanda ./examples/hello_world.ama
