name: linux-build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip3.8 install --upgrade pip
        pip3.8 install -r requirements.txt
    - name: Run build
      run: |
        python3.8 -m tests.test
        sudo $pythonLocation/bin/python3.8 setup.py
        dist/amanda ./examples/hello_world.ama
