name: macOS-build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run build
      run: |
        python3 -m tests.test
        sudo python3 setup.py
        amanda ./examples/hello_world.ama
